[providers]
php = ["extensions"]

[variables]
PHP_VERSION = "8.4"
NIXPACKS_PHP_EXTENSIONS = "mbstring, xml, ctype, iconv, mysql, pdo_mysql, zip, bcmath, filter, openssl"

[phases.setup]
nixPkgs = ["...", "php84", "php84Packages.composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "npm run build"]